// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    print('[FIREBASE_OPTIONS] Getting current platform options...');
    print('[FIREBASE_OPTIONS] kIsWeb: $kIsWeb');
    print('[FIREBASE_OPTIONS] defaultTargetPlatform: $defaultTargetPlatform');
    
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        print('[FIREBASE_OPTIONS] Returning Android options');
        return android;
      case TargetPlatform.iOS:
        print('[FIREBASE_OPTIONS] Returning iOS options');
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh9lSSlqM-Olm0ghsFyomxIjYaWmdnp-8',
    appId: '1:399888049122:android:14469b86a2f9d8ea034fbb',
    messagingSenderId: '399888049122',
    projectId: 'resynth-b44bb',
    databaseURL: 'https://resynth-b44bb-default-rtdb.firebaseio.com',
    storageBucket: 'resynth-b44bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9lSSlqM-Olm0ghsFyomxIjYaWmdnp-8',
    appId: '1:399888049122:ios:14469b86a2f9d8ea034fbb',
    messagingSenderId: '399888049122',
    projectId: 'resynth-b44bb',
    databaseURL: 'https://resynth-b44bb-default-rtdb.firebaseio.com',
    storageBucket: 'resynth-b44bb.firebasestorage.app',
    iosBundleId: 'com.resynth.vpn',
  );
}
